<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>async/await</title>
	</head>

	<body>
		<script>
			/**
			 * 1、async 函数
			 *    函数的返回值为promise对象
			 *    promise对象的结果由async函数执行的返回值决定
			 * 2、await 表达式
			 *    await右侧的表达式一般为promise对象，但也可以是其他的值
			 *    如果表达式是promise对象，await返回的是promise成功的值
			 *    如果表达式是其他值，直接将此值作为await的返回值
			 * 3、注意
			 *    await必须写在async函数中，但async函数中可以没有await
			 *    如果await的promise失败了，就会抛出异常，需要通过try...catch来捕获处理
			 */

			async function fn1() {
				// return 1;
				// throw 2;
				// return Promise.resolve(3);
				return Promise.reject(4);
			}
			const res = fn1();
			// console.log(res); // 一个状态为fulfilled的promise对象，value为1
			res.then(
				(value) => {
					console.log(value);
				},
				(reason) => {
					console.log(reason);
				}
			);

			function fn2() {
				return new Promise((resolve, reject) => {
					setTimeout(() => {
						// resolve(2);
						reject(2);
					}, 500);
				});
			}
			async function fn3() {
				// 1、如果表达式是状态为fulfilled的promise对象，则await返回的是promise对象的value
				// const value = await fn2();

				// 2、如果表达式是其他值，直接将此值作为await的返回值
				// const value = await 5;

				// console.log(value);

				///3、如果表达式是状态为rejected的promise对象，就会抛出异常，需要通过try...catch来捕获处理，error为reason
				try {
					const reason = await fn2();
				} catch (error) {
					console.log(error);
				}
			}
			fn3();

			setTimeout(() => {
				console.log("setTimeout");
			}, 0);

			Promise.resolve(1).then((value) => {
				console.log("onResolved", value);
			});
		</script>
	</body>
</html>
